### ISSUE TITLE
suggestion: why not a 3ds max plugin?

### ISSUE THREAD

**Issue by phamtheson01** [Perryvw/Blender-vmesh-plugin#4]
it's easier because blender is little bit harder to merge animations,bones correction and 3ds max is more popular than blender

**Comment by Perryvw** [comment]
Because I don't know how to write 3ds max plugins 😁 But feel free to adapt this plugin to other environments.

**Comment by phamtheson01** [comment]
3ds max or maya is better because blender has faces limit so it cant import the whole mesh into the program
but you should look into the blender source tool,they import the smd file perfectly but still have some problem when import the structures ( idk why ) but you should contact him to help u improve this project
make a animation importer too ( if you can )
