### ISSUE TITLE
Dota2 Ti9 new models can't open with the script

### ISSUE THREAD

**Issue by LGCaerwyn** [Perryvw/Blender-vmesh-plugin#5]
the models updated before Ti9 are fine.
need help!!! @Perryvw @Numbers11

**Comment by Perryvw** [comment]
Looking into this

**Comment by phamtheson01** [comment]
same problem,blender got freezee,old version import fine

**Comment by Perryvw** [comment]
Valve added new encoding for their model files that uses lz4 compression. I am having issues getting decompression to work in a blender plugin, I don't know if or when I will be able to fix this :/

**Comment by LEMBAS007** [comment]
> Valve added new encoding for their model files that uses lz4 compression. I am having issues getting decompression to work in a blender plugin, I don't know if or when I will be able to fix this :/

did you solve this problem? already a year has passed

**Comment by LGCaerwyn** [comment]
> > Valve added new encoding for their model files that uses lz4 compression. I am having issues getting decompression to work in a blender plugin, I don't know if or when I will be able to fix this :/
> 
> did you solve this problem? already a year has passed


just use old blender version 2.78/2.79, installing the plugin and blender source tools. it works fine now.
Also, we need the new plugin for blender 2.82.
